<!doctype html>
<html lang="en">

	<head>
		<meta charset="utf-8">

		<title>Fusion 360 API入门课程</title>

		<meta name="description" content="A framework for easily creating beautiful presentations using HTML">
		<meta name="author" content="Hakim El Hattab">

		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">

		<link rel="stylesheet" href="css/reveal.css">
		<link rel="stylesheet" href="css/theme/black.css" id="theme">

		<!-- Code syntax highlighting -->
		<link rel="stylesheet" href="lib/css/zenburn.css">

		<!-- Printing and PDF exports -->
		<script>
			var link = document.createElement( 'link' );
			link.rel = 'stylesheet';
			link.type = 'text/css';
			link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
			document.getElementsByTagName( 'head' )[0].appendChild( link );
		</script>

		<!--[if lt IE 9]>
		<script src="lib/js/html5shiv.js"></script>
		<![endif]-->
	</head>

	<body>

		<div class="reveal">

			<!-- Any section element inside of this container is displayed as a slide -->
			<div class="slides">
				<section>
					<h1>Fusion 360 API 入门</h1>
					<P></P>
					<P></P>
					<h3>梁晓冬</h3>
					<P></P>
				        <p><font size="6">开发顾问</font></p>
					<p><font size="6">DevTech中国区经理</font></p>
				</section>

				<section>
					<h2>内容</h2>
					<p>
						<ul>
						<li>Fusion 360 简介</li>
						<li>API 概览</li>
						<li>Javascript API</li>
						<li>Python API</li>
						<li>插件</li>
					</ul>
					</p>
				</section>
				
				<section>
					<h2>三维设计的新需求</h2>
					<p>					 
					<img width="800" height="400" data-src="images/3drequirement.jpg" alt="Down arrow">	
					</p>
				</section>
				
				<section>
					<h2>来看一个视频</h2>
					<p>					 
					<embed src="http://player.youku.com/player.php/sid/XOTQ3Nzk1MzUy/v.swf" allowFullScreen="true" quality="high" width="800" height="600" align="middle" allowScriptAccess="always" type="application/x-shockwave-flash"></embed>
					</p>
					<p><font size="5">注：广告都是浮云</font></p>
				</section>
				
				<section>
					<h2>Fusion 360</h2>
					<p>
					<font size="6">基于云，从概念设计到成品的三维CAD/CAM协作设计平台</font>
					<img width="600" height="400" data-src="images/fusion360.png" alt="Down arrow">	
					</p>
				</section>
				
				<section>
					<h2>新时代的设计概念</h2>
					<p>					
					<img width="800" height="500" data-src="images/workflow.png" alt="Down arrow">	
					</p>
				</section>
				
				<section>
					<h2>设计可以如此</h2>
					<p><a href="https://fusion360.autodesk.com/projects/editor_pick">Fusion 360 展台</a></p>
					<p>					
					<img width="800" height="500" data-src="images/desginlikethis.jpg" alt="Down arrow">	
					</p>
				</section>
				
				<section>
					<section id="fragments">
					<h2>谁在用</h2>	
					<ul>							
							<li><a href="http://modbot.com/">Modbot</a><p></p><img width="300" height="200" data-src="images/modbot.gif" alt="Down arrow"></li>							 
							<li><a href="http://www.lumitoro.com/pages/about-3d-printing">Lumitoro</a><p></p><img width="300" height="200" data-src="images/lumitoro.jpg" alt="Down arrow"></li>							 							
								 
					</ul>	
					</section>	
					<section id="fragments">					 
					<ul>							
							<li><a href="">公路赛车</a><p></p><img width="300" height="200" data-src="images/roadbike.png" alt="Down arrow"></li>							 
							<li><a href="">Local Motors</a><p></p><img width="300" height="200" data-src="images/localmobile.jpg" alt="Down arrow"></li>							 							 
								 
					</ul>	
					</section>
					
					<section id="fragments">					 
					<ul>														
							<li><a href="https://www.keyshot.com/">Keyshot</a><p></p><img width="500" height="400" data-src="images/keyshot.png" alt="Down arrow"></li>							 						 
								 
					</ul>	
					</section>
					
				</section>
				
				<section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom">
					<h1>API拓展?</h1> 
				</section>
				
				<section>
					<h2><a href="https://apps.exchange.autodesk.com/FUSION/en/Home/Index">程序赏析</a></h2>								
				</section>
				
				
				
				
				<section>
					<h2>Fusion API - 目前是客户端的API</h2>	
						<ul>							
								<li>脚本</li>								 								 
								<li>插件</li> 								 
						</ul>
					<p></p>							
					<img width="700" height="400" data-src="images/keywords.png" alt="Down arrow">	
				</section>
				
				<section>
					<section id="fragments-api-progress">
						<h2>API 演化过程</h2>					 					 
						<ul>							
								<li>2014年9月引入Javascript 脚本形式</li>								 
								<li>2014年11月引入Python脚本形式</li>								 
								<li>2015年3月推出插件形式</li> 
								<li>2015年8月推出C++的方式</li> 
								<li>多编程语言的背后是单一的API</li> 
								<li>为每种编程语言包装了接口</li> 							
						</ul>	
					</section>
					
				</section> 
				
					<section>
					<section id="fragments-api-ability">					
						<font size="8">2015年8月发布版支持的API （绿色部分）</font>					 					 
						<p></p>
						<font size="6">
						<ul>							
								<li>特征和时间轴</li>								 
								<li>草图, 构造特征</li>								 								 
								<li>参数</li>
								<li>材质,外观 </li>							 
								<li>基本的A360访问</li> 
						</ul>
						</font>	
						<img width="700" height="400" data-src="images/apiability1.bmp" alt="Down arrow">			
					</section>
					<section id="fragments-api-ability">
						<font size="6">
						<ul>							
								<li>装配结构, 约束</li>								 
								<li>BRep访问，三角网格</li>								 
								<li>用户设置</li> 
								<li>相机相关功能</li>
								<li>命令和用户菜单</li>								 						 
						</ul>	
						</font>	
						<img width="700" height="400" data-src="images/apiability2.bmp" alt="Down arrow">	
					</section>
					<section id="fragments-api-ability">
						<h4>未来功能</h4>	 
						<ul>	 				 
								<li>剩下还未支持的特征</li> 
								<li>T-Splines</li>
								<li>工程图</li>
								<li>机加工（CAM）</li>								 
								<li>更多...</li>								 								
						</ul>							 
					</section>
				</section> 
				
				<section  >		
					<section id="apitree">
					<h2>API对象图</h2>	
						<font size = "6">
						<ul>							
								<li>面向对象的层级结构</li>								 
								<li>API对象对应界面中的对象或功能</li>								 
								<li>对象是包含关系，而非继承关系</li> 
								<li>collection: 对象集合</li>
								<li>adsk：对象总接口</li>
									<ul>
										<li>adsk.core: 辅助对象</li>
										<li>adsk.Fusion: Fusion对象</li>
										<li>adsk.cAM: CAM对象 </li>										
									</ul>
 								
						</ul>	
						</font  >
						</section>  
					 
						<section id="apitree">
						<h2>API对象图</h2>	
							<li>Application: 通过adsk.core.Application.get();</li>
							 <img width="700" height="500" data-src="images/objtree.png" alt="Down arrow">	 
						</section> 
						
						<section id="apitree">
						<h2>顶层入口</h2>	
						<pre><code>
var ui;
   try {
	var app = adsk.core.Application.get();
	ui = app.userInterface;

	// Get the active design.
	var product = app.activeProduct;
	var design = adsk.fusion.Design(product);
	if (!design) {
		ui.messageBox('No active Fusion design');
		adsk.terminate();
		return;
}
						</pre></code>							 
						</section> 
						
			   </section> 
			   
			   	<section>					 
						<h2><a href="https://fusion360.autodesk.com/projects/editor_pick">在线帮助</a></h2>					 					 
						<img width="800" height="600" data-src="images/help.png" alt="Down arrow">	 
				</section>	
			   
			   <section>
					<h2>脚本与插件管理器</h2>						
					<img width="800" height="600" data-src="images/addinmanager.png" alt="Down arrow">	
				</section>
				
				<section>
					<h2>创建脚本或插件</h2>						
					<img width="800" height="600" data-src="images/createaddin.png" alt="Down arrow">	
				</section> 
				
				<section>					 
						 
						<section id="fragments-script-addin">					
							<h2>脚本和插件</h2>	
							<ul>							
									<li>脚本类似于宏命令</li>								 
									<li>插件一般是Fusion启动时就加载运行</li>								 
									<li>插件用来创建用户界面，按钮等</li>								 
									<li>插件需要额外的manifest文件做配置</li> 
									<li>需要特别独立的功能时可考虑插件</li>
									<li>脚本方式可用manifest方式，也可不用</li>								 
							</ul> 		
						</section>
						<section id="fragments-script-addin"> 
							<h2>manifest文件 (Javascript)</h2>	
							<pre><code data-trim >
 {
	"autodeskProduct":	"Fusion360",
	"type":	"addin",
	"id":	"ea34afff-f444-4ac7-95e5-d9ac5c574b6e",
	"author":	"Autodesk Inc.",
	"description":	{
		"":	"This is sample addin."
	},
	"version":	"0.0.1",
	"runOnStartup":	false,
	"supportedOS":	"windows|mac",
	"autodeskLibraries":	["application", "dashboard", "geometry", "materials", "userInterface", "utilities", "bRep", "components", "construction", "features", "fusion", "meshBody", "meshData", "sketch", "tSpline"]
}
					</code></pre>
						</section>
						
					<section id="fragments-script-addin"> 
							<h2>manifest文件 (Python)</h2>	
							<pre><code data-trim >
 {
    "autodeskProduct":"Fusion360",
    "type":"addin",
    "id":"319679C5-AF6D-4A46-862D-93414F1AE117",
    "author":"Autodesk Inc.",
    "description":{
        "":"This is sample addin."
    },
    "version":"0.0.1",
    "runOnStartup":false,
    "supportedOS":"windows|mac"
}
					</code></pre>
						</section>	 
					
				</section>
				
				
					<section>					 
						 
						<section id="fragments-ide">					
							<h2>编辑和调试器 （Javascript）</h2>	
							 <img width="800" height="600" data-src="images/js-editor.png" alt="Down arrow">	
						</section>
						
						<section id="fragments-ide">					
							<h2>编辑和调试器 （Javascript）</h2>	
							 <img width="800" height="600" data-src="images/js-debug.png" alt="Down arrow">	
						</section>
						
						<section id="fragments-ide"> 
							 <h2>编辑和调试器 Python</h2>	
							 <img width="800" height="600" data-src="images/python-editor.png" alt="Down arrow">	
						</section>
						
					<section id="fragments-ide"> 
							 <h2>编辑和调试器 C++</h2>	
							 <img width="800" height="600" data-src="images/cpp-editor.png" alt="Down arrow">	
					 
					</section>	 

					<section id="fragments-ide"> 
							 <h2>编辑和调试器 C++</h2>	
							 
							 <img width="800" height="500" data-src="images/cpp-debug.png" alt="Down arrow">	
					 
					</section>	 						
				</section> 
			   
			   
			   <section>
			   <h2>C++特定问题</h2>
 <ul>			   
		<li>自动生成Visual Studio (.vcxproj) 和Xcode (.xcodeproj)。需用对应编译器编译</li>
							  <li>定义对象用智能指针</li>
					<pre><code data-trim contenteditable>
Ptr< SketchLine > line1;
bool doAnimation(Ptr< SketchCurve > pathCurve, Ptr< Vector3D > upDirection)
					</code></pre>	
								<li>操作对象属性</li>					
							<pre><code data-trim contenteditable>
if (comp->name() == "Test")
    bool isOK = comp->name("New Test"); 

					</code></pre>		
							  </ul>
							  
			   </section>
					
				<section>
					<h2>Components</h2>						
					<img width="800" height="600" data-src="images/Components.png" alt="Down arrow">	
				</section>
				
				<section>
					<h2>Input对象</h2>						
					<li>类似UI中的输入参数对话框 </li>						
					<li>配置造型的各种参数 </li>						
					<img width="300" height="300" data-src="images/inputobj.png" alt="Down arrow">	
					<pre><code>
 var prof = sketch.profiles.item(0); 
var extrudes = rootComp.features.extrudeFeatures;
var extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.NewBodyFeatureOperation); 
var distance = adsk.core.ValueInput.createByReal(5);
extInput.setDistanceExtent(false, distance);
 
var ext = extrudes.add(extInput)

						</pre></code>
							 
				</section>
				
				
					 <section>
					<section id="fragments-create-extrude">
						<h2>草图和特征</h2>				 					 
						<ul>							
									<li>草图（Sketch）：常规实体创建的构造轮廓</li>								 
									<li>特征（Feature）：最终看到的实体</li>								 									 
							</ul> 		
						<img width="800" height="500" data-src="images/extrudef.bmp" alt="Down arrow">	
					</section>
					<section id="fragments-create-extrude">										 					 
					<h2>创建拉伸特征（Python）</h2>	
						 <pre><code data-trim contenteditable>
app = adsk.core.Application.get()
design = app.activeProduct

# Get the root component of the active design. 
rootComp = design.rootComponent 

# Create a new sketch on the xy plane. 
sketch = rootComp.sketches.add(rootComp.xYConstructionPlane) 

# Draw a circle. 
circles = sketch.sketchCurves.sketchCircles 
circle1 = circles.addByCenterRadius(adsk.core.Point3D.create(0, 0, 0), 2) 

# Get the profile defined by the circle. 
prof = sketch.profiles.item(0) 

# Create an extrusion input to be able to define the input needed for an extrusion 
# while specifying the profile and that a new component is to be created 
extrudes = rootComp.features.extrudeFeatures 
extInput = extrudes.createInput(prof, adsk.fusion.FeatureOperations.NewComponentFeatureOperation) 

# Define that the extent is a distance extent of 5 cm. 
extInput.setDistanceExtent(False, adsk.core.ValueInput.createByReal(5)) 

# Create the extrusion. 
ext = extrudes.add(extInput) 

					</code></pre>	
					</section> 
				</section> 
				
				
					<section>
					<h2>Models </h2>						
					<img width="800" height="600" data-src="images/model.png" alt="Down arrow">	
				</section>
				
				<section>
					<section id="fragments-selection">	
					<h2>选择集 </h2> 
					<ul>							
							<li>用户选择实体的集合：application.userInterface.activeSelections</li>								 
							<li>每个选择实体的API对象：Selection</li> 
							<li>Selection：Selection</li> 
					 </ul> 		
					 </section>
					 <section id="fragments-selection">	
					 <h2>JavaScript对象类型与比较 </h2> 
					 	 <pre><code data-trim contenteditable>
var app = adsk.core.Application.get();
ui = app.userInterface;

 
var thisobj = ui.activeSelections.item(0).entity ;
var objName =    thisobj.objectType;
 ui.messageBox(objName);
if(thisobj instanceof adsk.fusion.BRepFace)
{
	  ui.messageBox("这是Face！");
}
else
{
	  ui.messageBox("这不是Face！");

}

if(ui.activeSelections.count>1)
{
	var thisobj1 = ui.activeSelections.item(0).entity;
	var thisobj2 = ui.activeSelections.item(1).entity;
	
	if(thisobj.equals(thisobj1)){
		
		 ui.messageBox("两对象相等！");
	}
	else{
		 ui.messageBox("两对象不相等！");
	}
}

					</code></pre>	
					
					  </section>
					  
					   <section id="fragments-selection">	
					 <h2>Pythont对象类型与比较 </h2> 
					 <pre><code data-trim contenteditable>
app = adsk.core.Application.get()
ui  = app.userInterface 
thisobj= ui.activeSelections.item(0).entity
objName = type(thisobj).__name__
if type(thisobj) is adsk.fusion.BRepFace:
	ui.messageBox('这是Face！')   
else:
	ui.messageBox('这不是Face！') 
            
if  ui.activeSelections.count > 1:
	thisobj1= ui.activeSelections.item(0).entity
	thisobj2= ui.activeSelections.item(1).entity
	if thisobj == thisobj1:
		ui.messageBox('两对象相等') 
	else:
		ui.messageBox('两对象不相等')  	

					</code></pre>	
					
					  </section>
					  
					   <section id="fragments-selection">	
					 <h2>C++对象类型与比较 </h2> 
					 	 <pre><code data-trim contenteditable>
 Ptr<Base> selectedEnt = selection->entity(); 
if (selectedEnt->objectType() == adsk::fusion::SketchLine::classType())

If (face1 == face2)
    ui.messageBox(“Faces are the same.”);

					</code></pre>	
					
					  </section>
				</section> 
					
				 <section>
				 <h2>练习</h2>
				 <h3>选择某平面，基于平面创建草图，绘制矩形，根据此轮廓，创建一定长度的拉伸特征</h3>
				 </section>
				 
				 <section>
				
				 <section id="fragments-addin-structure">
				  <h2>插件基本结构(JavaScript)</h2>
 <pre><code data-trim contenteditable>
function run(context) {

    "use strict";
    if (adsk.debug === true) {
        /*jslint debug: true*/
        debugger;
        /*jslint debug: false*/
    }

    var ui;
    try {
        var app = adsk.core.Application.get();
        ui = app.userInterface;

        ui.messageBox('Hello addin');
    }
    catch (e) {
        if (ui) {
            ui.messageBox('Failed : ' + (e.description ? e.description : e));
        }
    }
}

function stop(context) {
    var ui;
    try {
        var app = adsk.core.Application.get();
        ui = app.userInterface;

        ui.messageBox('Stop addin');
    }
    catch (e) {
        if (ui) {
            ui.messageBox('Failed : ' + (e.description ? e.description : e));
        }
    }
} 
					</code></pre>	
					
				  </section>
				   <section id="fragments-addin-structure">	
				   <h2>插件基本结构(Python)</h2>
				    <pre><code data-trim contenteditable>
 
def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        ui.messageBox('Hello addin')

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))

def stop(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        ui.messageBox('Stop addin')

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
  
					</code></pre>	
				  </section>
				  
				   <section id="fragments-addin-structure">
				  <h2>插件基本结构(C++)</h2>
 <pre><code data-trim contenteditable>
 
#include <Core/CoreAll.h>
#include <Fusion/FusionAll.h>


using namespace adsk::core;
using namespace adsk::fusion;

Ptr<Application> app;
Ptr<UserInterface> ui;

extern "C" XI_EXPORT bool run(const char* context)
{
	app = Application::get();
	if (!app)
		return false;

	ui = app->userInterface();
	if (!ui)
		return false;

	ui->messageBox("in run");

	return true;
}

extern "C" XI_EXPORT bool stop(const char* context)
{
	if (ui)
	{
		ui->messageBox("in stop");
		ui = nullptr;
	}

	return true;
}


#ifdef XI_WIN

#include <windows.h>

BOOL APIENTRY DllMain(HMODULE hmodule, DWORD reason, LPVOID reserved)
{
	switch (reason)
	{
	case DLL_PROCESS_ATTACH:
	case DLL_THREAD_ATTACH:
	case DLL_THREAD_DETACH:
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

#endif // XI_WIN

					</code></pre>	
					
				  </section>
				  
				 </section>
				 
				 
				 
				
				<section>
					<section id="fragments-event">	
						<h2>事件</h2>	
					<ul>
					<li>定义事件函数</li>	
					<li>添加函数指针到对应事件</li>		 
					</ul> 		
					 </section> 
					   <section id="fragments-event">	
					 <h2>事件(JavaScript) </h2> 
					 <pre><code data-trim contenteditable>
  //定义事件函数
 var MyWorkspaceActivatedHandler = function(args) {
      var ws = args.workspace;
      var app = adsk.core.Application.get();
      var ui  = app.userInterface;
      ui.messageBox(ws.name + ' workspace was activated (JavaScript).');        
  };    
  //添加函数指针到对应事件
  function run(context) {
      var app = adsk.core.Application.get();
      var ui = app.userInterface;
      ui.workspaceActivated.add(MyWorkspaceActivatedHandler);
      ui.messageBox('Event connected.');
  } 
} 

					</code></pre>	
					
					  </section>
					 <section id="fragments-event">	
					 <h2>事件(Python) </h2> 
					<pre><code data-trim contenteditable>
  
					</code></pre>	
					
					</section> 
					   <section id="fragments-event">	
					 <h2>事件(C++) </h2> 
					 	 <pre><code data-trim contenteditable>
 
					</code></pre>	
					
					  </section>
				</section> 
				
				<section>
					<section id="fragments-ui">	
						<h2>命令和用户界面</h2>	
					<ul>
						<li>命令</li>
							<ul>
							<li>Definition: 定义Command名，事件，图标…</li>	
							 
								<li>userInterface.commandDefinitions: definition 集合</li>
								<li>各种类型按钮添加方法，例如commandDefinitions.addButtonDefinition</li>
								<li>定义命令执行事件</li>
							 </ul>
						<li>Controls: 关联Definition的UI界面</li>	 
							<ul>
								<li>userInterface.workspaces: Model, Render, CAM...</li>
								<li>workspace.toolbarPanels: workspace下的所有面板</li>
								<li>panel.controls: 面板下的命令</li>
								<li>controls.addCommand: 将definition添加到该面板</li>
							</ul> 
						 
					</ul> 		
					 </section>
					 <section id="fragments-ui">	
					 <h2>命令和用户界面(Python) </h2> 
					<pre><code data-trim contenteditable>
import adsk.core, adsk.fusion, traceback

app = None
ui = None
handlers_dialog = []
commandDefId = 'ADNTestCommandDef'
commandName = 'My Test'
commandDescription = 'test'
workspaceToUse = "FusionSolidEnvironment"
panelToUse = "SolidCreatePanel" 

class CommandCreatedHandler(adsk.core.CommandCreatedEventHandler):
    def __init__(self):
        super().__init__()
    def notify(self, args):
        global ui
        ui.messageBox('我的按钮执行了！')
        
def run(context):
   
    try:
        global app
        app = adsk.core.Application.get()
        global ui
        ui = app.userInterface
        
        ui.messageBox('Hello addin')
        
        #添加命令的definition
        cmdDef = ui.commandDefinitions.itemById(commandDefId)
        if not cmdDef:
            cmdDef = ui.commandDefinitions.addButtonDefinition(commandDefId, commandName, commandDescription, '/')
            
        onCommandCreated = CommandCreatedHandler()
        cmdDef.commandCreated.add(onCommandCreated)
        
        #工作空间
        workspaces_ = ui.workspaces
        modelingWorkspace_ = workspaces_.itemById(workspaceToUse)
        # 面板
       
        toolbarPanels_ = modelingWorkspace_.toolbarPanels
        toolbarPanel_ = toolbarPanels_.itemById(panelToUse)
        
        #面板按钮集合
        toolbarControlsPanel_ = toolbarPanel_.controls
        toolbarControlPanel_ = toolbarControlsPanel_.itemById(commandDefId)
        if not toolbarControlPanel_:
            toolbarControlPanel_ = toolbarControlsPanel_.addCommand(cmdDef, commandDefId)

        
        #handlers_dialog.append(onCommandCreated)        

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))

def stop(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui  = app.userInterface
        ui.messageBox('Stop addin')
        
        workspaces_ = ui.workspaces
        modelingWorkspace_ = workspaces_.itemById(workspaceToUse)
        toolbarPanels_ = modelingWorkspace_.toolbarPanels
        toolbarPanel_ = toolbarPanels_.itemById(panelToUse)
        toolbarControls_ = toolbarPanel_.controls
        toolbarControl_ = toolbarControls_.itemById(commandDefId)
        
        if toolbarControl_.isValid:
            toolbarControl_.deleteMe()
        commandDefinitions_ = ui.commandDefinitions
        commandDefinition_ = commandDefinitions_.itemById(commandDefId)
         
        if commandDefinition_.isValid:
            commandDefinition_.deleteMe()

    except:
        if ui:
            ui.messageBox('Failed:\n{}'.format(traceback.format_exc()))
 
					</code></pre>	
					
					</section>
					  
					   <section id="fragments-ui">	
					 <h2>命令和用户界面(JavaScript) </h2> 
					 <pre><code data-trim contenteditable>


					</code></pre>	
					
					  </section>
					  
					   <section id="fragments-ui">	
					 <h2>命令和用户界面(C++) </h2> 
					 	 <pre><code data-trim contenteditable>
 
					</code></pre>	
					
					  </section>
				</section> 				
				
				 <section>
					<h2>用户界面</h2>		
					<ul>
					<li>Definition: 定义Command名，事件，图标…</li>	
					<li>Controls: 关联Definition的UI界面</li>		 
					</ul> 
					 			
					<img width="700" height="500" data-src="images/ui.png" alt="Down arrow">	
					 
							 
				</section> 
				 
			

				
				<section>
					<section id="fragments-hackathon">	
					<h2><a href="http://blog.csdn.net/autodeskinventorapi/article/details/48367381/">发布Fusion 360程序，拿500刀！</a></h2>		
 					</section>
					
					<section id="fragments-hackathon">	
					<h1>500刀！！！</h1>								
					</section>
					
				</section>

			

				<section>					 
						<h2>Javascript</h2>					 					 
						<ul>							
								<li>不能使用额外的HTML界面</li>								 
								<li>无法访问本地文件系统</li>								 
								<li>可用任何编辑器编写，或使用Fusion内置的Bracket</li> 
								<li>借用Chrome或Webkit进行调试</li>
								<li>进程外运行</li>
								<li>可加载第三方JS库（和HTML界面相关的除外）</li>								 
						</ul> 
				</section>	

				<section>					 
						<h2>Python</h2>					 					 
						<ul>							
								<li>运行于Fusion进程内</li>								 
								<li>比JS要快</li>								 
								<li>可访问本地文件系统</li> 
								<li>可用任何编辑器编写，或使用Fusion内置的Spyder</li>
								<li>用Spyder调试</li>
								<li>可加载第三方Python库</li>								 
						</ul> 
				</section>	 
				
				<section>					 
						<h2>Fusion命令</h2>					 					 
						<ul>							
								<li>脚本和插件都可以用</li>								 
								<li>Fusion自己大部分功能也都是命令的方式</li>								 
								<li>命令一般对应一个按钮，而按钮背后是一个'定义'，规定执行按钮的相关行为</li> 
								<li>按钮执行时，命令创建启动</li>
								<li>可弹出参数输入对话框，用来得到命令需要的数据</li>								 
								<li>可预览参数产生的效果</li>	
								<li>自动支持事务，可回滚</li>	
						</ul> 
				</section>

				 
				
			
				
				<section>
					<h1>参考资料</h1> 
					<ul>							
							<li><a href="http://fusion360.autodesk.com/resources">在线帮助</a></li>	
							<P></P>	
							<li><a href="http://modthemachine.typepad.com/">Brian的博客</a></li>	
							<P></P>	
							<li><a href="http://adndevblog.typepad.com/manufacturing/">ADN制造业博客</a></li>	
							<P></P>								
							<li><a href="http://forums.autodesk.com/t5/Autodesk-Fusion-360/ct-p/1234">论坛</a></li>	
							<P></P>								 							 
					</ul>	
				</section>

				<section>
					<h2>Autodesk ADN 微信公众号</h2>
					 <img width="300" height="300" data-src="images/wechat.jpg" alt="Down arrow">	
 					 <h6> <a href="http://blog.csdn.net/autodeskinventorapi">我的博客</a></h6>
				</section> 	

				<section>
					 <img width="800" height="600" data-src="images/Autodesk.png" alt="Down arrow">	
				</section>  				

				
			</div>

		</div>

		<script src="lib/js/head.min.js"></script>
		<script src="js/reveal.js"></script>

		<script>

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		</script>

	</body>
</html>
